import { describe, it, expect, afterAll } from 'vitest'
import * as fs from 'fs'
import * as path from 'path'
import { Generator } from '../../../src/generator/index.js'
import {
    isGeneratedOutputFresh,
    generatedFileNames,
} from '../../../src/cli/commands/generate.js'
import { check } from '../../../src/cli/commands/check.js'
import { buildInitScripts, init } from '../../../src/cli/commands/init.js'
import {
    readValidationMode,
    readClientHeaderConst,
} from '../../../src/shared/client-header.js'
import { mockSchema } from '../generator/fixtures/mock-schema.js'

const dirs: string[] = []

// Inside the repo so generation resolves the installed zod
function outputDir(): string {
    const base = path.join(process.cwd(), 'node_modules', '.tmp')
    fs.mkdirSync(base, { recursive: true })
    const dir = fs.mkdtempSync(path.join(base, 'validation-mode-'))
    dirs.push(dir)
    return dir
}

afterAll(() => {
    for (const dir of dirs) fs.rmSync(dir, { recursive: true, force: true })
})

const files = (dir: string) =>
    fs.readdirSync(dir).filter(f => f.startsWith('validation'))

describe('validation mode stamp', () => {
    it.each(['ts', 'js'] as const)(
        'is readable back from a %s client, next to a long prerelease version',
        async format => {
            const dir = outputDir()
            await new Generator(dir).generate(mockSchema, {
                format,
                validation: 'zod',
                schemaHash: 'a'.repeat(64),
                generatorVersion: '12.34.56-beta.20261007T101010.abcdef',
            })
            expect(readValidationMode(dir)).toBe('zod')
            expect(readClientHeaderConst(dir, 'SCHEMA_HASH')).toBe(
                'a'.repeat(64),
            )
        },
    )

    it('reads none from a client generated without validators', async () => {
        const dir = outputDir()
        await new Generator(dir).generate(mockSchema, { format: 'ts' })
        expect(readValidationMode(dir)).toBe('none')
    })

    it('is null for a client generated before the stamp existed', () => {
        const dir = outputDir()
        fs.writeFileSync(
            path.join(dir, 'client.ts'),
            'export const SCHEMA_HASH = "x"\nexport const GENERATOR_VERSION = "2.2.1"\n',
        )
        expect(readValidationMode(dir)).toBeNull()
    })
})

describe('validation files in the output dir', () => {
    it('removes its own validators once validation is turned off', async () => {
        const dir = outputDir()
        await new Generator(dir).generate(mockSchema, {
            format: 'js',
            validation: 'zod',
        })
        expect(files(dir)).toEqual(['validation.d.ts', 'validation.js'])
        await new Generator(dir).generate(mockSchema, { format: 'js' })
        expect(files(dir)).toEqual([])
    })

    it('drops the other format when switching while validation stays on', async () => {
        const dir = outputDir()
        await new Generator(dir).generate(mockSchema, {
            format: 'ts',
            validation: 'zod',
        })
        await new Generator(dir).generate(mockSchema, {
            format: 'js',
            validation: 'zod',
        })
        expect(files(dir)).toEqual(['validation.d.ts', 'validation.js'])
    })

    it('never overwrites a validation.ts it did not write', async () => {
        const dir = outputDir()
        fs.writeFileSync(
            path.join(dir, 'validation.ts'),
            'export const mine = 1\n',
        )
        await expect(
            new Generator(dir).generate(mockSchema, {
                format: 'ts',
                validation: 'zod',
            }),
        ).rejects.toThrow(/was not generated by strapi-typed-client/)
        expect(fs.readFileSync(path.join(dir, 'validation.ts'), 'utf-8')).toBe(
            'export const mine = 1\n',
        )
        expect(fs.existsSync(path.join(dir, 'client.ts'))).toBe(false)
    })

    it('refuses to write validators next to a foreign file of the other format', async () => {
        const dir = outputDir()
        fs.writeFileSync(
            path.join(dir, 'validation.ts'),
            'export const mine = 1\n',
        )
        await expect(
            new Generator(dir).generate(mockSchema, {
                format: 'js',
                validation: 'zod',
            }),
        ).rejects.toThrow(/was not generated by strapi-typed-client/)
        expect(files(dir)).toEqual(['validation.ts'])
    })

    it('never deletes a validation.ts it did not write', async () => {
        const dir = outputDir()
        fs.writeFileSync(
            path.join(dir, 'validation.ts'),
            'export const mine = 1\n',
        )
        await new Generator(dir).generate(mockSchema, { format: 'ts' })
        expect(files(dir)).toEqual(['validation.ts'])
    })
})

describe('freshness', () => {
    const base = {
        localHash: 'abc',
        remoteHash: 'abc',
        localVersion: '2.3.0',
        cliVersion: '2.3.0',
        allFilesExist: true,
    }

    it('regenerates when the validation mode changes on an otherwise fresh tree', () => {
        expect(
            isGeneratedOutputFresh({
                ...base,
                localValidation: 'none',
                validation: 'zod',
            }),
        ).toBe(false)
        expect(
            isGeneratedOutputFresh({
                ...base,
                localValidation: 'zod',
                validation: 'zod',
            }),
        ).toBe(true)
    })

    it('treats an unstamped tree as none', () => {
        expect(
            isGeneratedOutputFresh({
                ...base,
                localValidation: null,
                validation: 'none',
            }),
        ).toBe(true)
    })

    it('expects the validation files among the generated ones', () => {
        expect(generatedFileNames('ts', 'zod')).toContain('validation.ts')
        expect(generatedFileNames('js', 'zod')).toEqual(
            expect.arrayContaining(['validation.js', 'validation.d.ts']),
        )
        expect(generatedFileNames('js', 'none')).not.toContain('validation.js')
    })
})

describe('check', () => {
    it('is out of sync when stamped validators are missing', async () => {
        const dir = outputDir()
        await new Generator(dir).generate(mockSchema, {
            format: 'ts',
            validation: 'zod',
            schemaHash: 'h',
        })
        fs.rmSync(path.join(dir, 'validation.ts'))
        const result = await check({ output: dir, silent: true })
        expect(result.inSync).toBe(false)
        expect(result.error).toMatch(/validation\.ts is missing/)
    })
})

describe('init', () => {
    it('bakes --validation zod into the generate script only', () => {
        const scripts = buildInitScripts({
            output: './src/strapi',
            format: 'ts',
            validation: 'zod',
        })
        expect(scripts['strapi:generate']).toBe(
            'strapi-types generate --output ./src/strapi --format ts --validation zod',
        )
        expect(scripts['strapi:check']).toBe(
            'strapi-types check --output ./src/strapi',
        )
    })

    it('rejects an unknown validation mode', async () => {
        const dir = outputDir()
        fs.writeFileSync(path.join(dir, 'package.json'), '{"name":"app"}\n')
        const result = await init({
            cwd: dir,
            validation: 'yup',
            yes: true,
            silent: true,
        })
        expect(result.success).toBe(false)
        expect(result.error).toMatch(/Invalid --validation value: yup/)
    })
})
